version: '3.4'

services:

  rabbitmq:
    image: re-rabbitmq
    build:
      context: ./Infrastructure/rabbitmq/
    volumes:
      - './Infrastructure/rabbitmq/config/rabbitmq_definitions.json:/etc/rabbitmq/rabbitmq_definitions.json'

  redis.cache:
    image: redis
