version: '3.4'

services:

  rabbitmq:
    image: re-rabbitmq
    build:
      context: ./Infrastructure/rabbitmq/
    ports:
      - '15672:15672'
      - '5672:5672'
    volumes:
      - './Infrastructure/rabbitmq/config/rabbitmq_definitions.json:/etc/rabbitmq/rabbitmq_definitions.json'

  redis.cache:
    image: redis
    ports:
      - "6379:6379"
