version: '3.4'

services:

  samplewebapplication:
    image: samplewebapplication
    build:
      context: .
      dockerfile: ./Sample/SampleWebApplication/Dockerfile

  rabbitmq:
    image: re-rabbitmq
    build:
      context: ./Infrastructure/rabbitmq/

  redis.cache:
    image: redis
